### ISSUE TITLE
No ingresa a Actualizacion de precios

### ISSUE THREAD

**Issue by AleGauna** [fproldan/erpnext#7]
No se puede ingresar a Actualizacion precio de producto, V11. 

Traceback (most recent call last):
  File "/home/erp/erpnext/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/home/erp/erpnext/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/erp/erpnext/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/erp/erpnext/apps/frappe/frappe/__init__.py", line 1020, in call
    return fn(*args, **newargs)
  File "/home/erp/erpnext/apps/frappe/frappe/desk/form/load.py", line 71, in getdoctype
    docs = get_meta_bundle(doctype)
  File "/home/erp/erpnext/apps/frappe/frappe/desk/form/load.py", line 81, in get_meta_bundle
    bundle = [frappe.desk.form.meta.get_meta(doctype)]
  File "/home/erp/erpnext/apps/frappe/frappe/desk/form/meta.py", line 26, in get_meta
    meta = FormMeta(doctype)
  File "/home/erp/erpnext/apps/frappe/frappe/desk/form/meta.py", line 39, in __init__
    self.load_assets()
  File "/home/erp/erpnext/apps/frappe/frappe/desk/form/meta.py", line 49, in load_assets
    self.add_code()
  File "/home/erp/erpnext/apps/frappe/frappe/desk/form/meta.py", line 101, in add_code
    self.add_html_templates(path)
  File "/home/erp/erpnext/apps/frappe/frappe/desk/form/meta.py", line 113, in add_html_templates
    for fname in os.listdir(path):
OSError: [Errno 2] No such file or directory: '/home/erp/erpnext/apps/erpnext_price_list_update/erpnext_price_list_update/price_list_update/doctype/actualizacion_precio_producto'

**Comment by AleGauna** [comment]
Ya esta funcionando bien.

**Comment by Don-Leopardo** [comment]
Bueno, habría que pasar la tarjeta a tested y acordarse que esto esta en la rama v2. Hay que ver si mergeamos a master luego.

**Comment by federicocalvo** [comment]
@AleGauna si ale vos probás y funciona bien, confirmalo y @Don-Leopardo ya lo mergeas a master y la pasas a closed

**Comment by AleGauna** [comment]
Funciona OK

**Comment by Don-Leopardo** [comment]
@ValentinaPruvost Si queres se puede volver a probar ahora que esta mergeado en master

**Comment by ValentinaPruvost** [comment]
@Don-Leopardo factura_electronica_ar?
